{% set name = "pyqode.core" %}
{% set version = "4.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fdfe2216924fb7903688d1ea3e2bfeefd2a3877028c21bf40758319306e9d413

build:
  number: 0
  noarch: python
  preserve_egg_dir: true
  entry_points:
    - pyqode-console = pyqode.core.tools.console:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - future
    - pip
    - pygments
    - pyqode.qt
    - python
    - setuptools
  run:
    - future
    - pygments
    - pyqode.qt
    - python
    - setuptools

test:
  imports:
    - pyqode
    - pyqode.core
    - pyqode.core._designer_plugins
    - pyqode.core._forms
    - pyqode.core.api
    - pyqode.core.backend
    - pyqode.core.dialogs
    - pyqode.core.managers
    - pyqode.core.modes
    - pyqode.core.panels
    - pyqode.core.styles
    - pyqode.core.tools
    - pyqode.core.widgets
  commands:
    - echo input > input.txt
    - pyqode-console < input.txt
  requires:
    - pyqt

about:
  home: https://github.com/pyQode/pyqode.core
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: PyQt/PySide Source Code Editor Widget
  doc_url: https://github.com/pyQode/pyQode/wiki
  dev_url: https://github.com/pyQode/pyQode

extra:
  recipe-maintainers:
    - ericpre
