{% set name = "pyqode.core" %}
{% set version = "4.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyqode-core-{{ version }}.tar.gz
  sha256: 93bf7909a36e64a9e4e017ad43c8e82bb1112e9583d5591bd50c7e1699b88b85

build:
  number: 0
  noarch: python
  entry_points:
    - pyqode-console = pyqode.core.tools.console:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv'

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
  run:
    - future
    - pathspec
    - pygments
    - python >={{ python_min }}
    - qtpy
    - qtawesome

test:
  imports:
    - pyqode
    - pyqode.core
    - pyqode.core._designer_plugins
    - pyqode.core._forms
    - pyqode.core.api
    - pyqode.core.backend
    - pyqode.core.dialogs
    - pyqode.core.managers
    - pyqode.core.modes
    - pyqode.core.panels
    - pyqode.core.styles
    - pyqode.core.tools
    - pyqode.core.widgets
  commands:
    - echo input > input.txt
    - pyqode-console < input.txt
  requires:
    - python {{ python_min }}
    - pyqt

about:
  home: https://github.com/pyQode/pyqode.core
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: PyQt/PySide Source Code Editor Widget
  doc_url: https://github.com/open-cogsci/pyqode.core
  dev_url: https://github.com/open-cogsci/pyqode.core

extra:
  recipe-maintainers:
    - ericpre
