travis:
  secure:
    BINSTAR_TOKEN: MCRQqTEIy/p6YBNxp4lkFpMjgRi5e5NWhHn+EBhlP4uoDHCwjbDZ1c/jDNQxne/HUnCJPxLK0uY83aC3B3R9+tfaKpxBU7bmZhVsJHlfMPq96dJkBkdGcUdouwkFQj2kAoC4KQVASQRClAIEpXoQayp77g38/pyttz+LsLNPURtHpMu6TsjJQjSZK+b4AekoXSvC5xkbvYeWe2DLR8Av2JC3oAItPmuqiF+NjndmNd5W+l2XwjZMoo/tXwURVU8NB7y0ETEpsFHu8S6VG6Q2S8DYdVVy0Xg6U6OxGwgfS/i2w15pMyUUeDQQHQW6FgUOKC91xTstdoacRCOZyyfJGEZSAaak11nF/thc8BB2TJXUoavmUFJ5QZiA+W8h7GvPArs9B52pbqwExjUoWTPyeUXvMkboMdBdmMZwva0iEuF0IK/LXIspUeUe5qQ0ZnQTTxCMhxXOTWFNvRYhfOiLKq/IENpZfv8CVK7owxOkvXytdbCAKHR87Mn42SS3NIM6ZB3xE3h2sWD+2CpEO/dpy5wpLMlBiek05a5hvh9BBlhj4j+82h0hwnOYv6f/t29hlV3Ntdu/7w8ZtrRSBH+uIkzftd+4wlERIPrmtDaP3eO9rRpo4Sw1YyKpzNg7iHeQ4v1D+M1iO7I1+JjC3fxBQbDE2s1RqnJQtXlLkGllnk8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
